[project]
name = "pulse-mobile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faicons>=0.2.2",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "shiny[theme]>=1.5.0",
    "shinywidgets>=0.7.0",
]
